name: autoforen_x
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  local_auth: ^2.1.7
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0 
  camera: ^0.11.1
  path_provider: ^2.1.2  
  flutter_sound: ^9.2.13  # Audio recording & playback
  permission_handler: ^11.0.1  # Manage permissions (camera, mic, location)
  geolocator: ^13.0.2  # Get GPS location metadata
  device_info_plus: ^11.3.3  # Fetch device ID & model
  intl: ^0.19.0  # Timestamp formatting
  flutter_bloc: ^9.1.0  # For state management
  crypto: ^3.0.3 # Quantum hash verification (SHA256, SHA512, etc.)
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.9
  provider: ^6.1.2
  video_player: ^2.8.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.2.2
  share_plus: ^10.1.4
  web3dart: ^2.6.1
  biometric_storage: 5.0.1
  shared_preferences: ^2.2.1
  fl_chart: ^0.70.2
  flutter_local_notifications: ^18.0.1
  pdf: ^3.10.8
  firebase_core: ^3.12.0        # Required for Firebase services
  firebase_messaging: ^15.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.6.4
  expansion_tile_card: ^3.0.0
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.1.14
  flutter_chat_ui: ^1.6.12
  flutter_map: ^8.1.0
  flutter_animate: ^4.5.2
  timeline_tile: ^2.0.0
  iconsax: ^0.0.8
  sensors_plus: ^3.1.0
  glassmorphism: ^3.0.0
  flutter_3d_controller: ^1.1.1
  latlong2: ^0.9.0
  speech_to_text: ^7.0.0
  flutter_hooks: ^0.20.5
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/quantum_animation.json

  uses-material-design: true
